### PR TITLE
add relay.nostr.info

### PR DESCRIPTION
**Pull request by Giszmo**

### CODE REVIEW

**Comment by fiatjaf** [comment]
You are welcome!

**Comment by Giszmo** [comment]
Thank you. Sorry for not asking politely. Just went with the commit message.

**Comment by fiatjaf** [comment]
No, please do not ask politely. Just throw the commits. I wasn't saying you should have said "thank you" or anything like that (in fact I believe the etiquette says I should be the one saying "thank you for your contribution"), I was making a half joke saying your relay was welcome in this repository.

**Comment by Giszmo** [comment]
I took it as sarcasm to a missing "please". Great to know we are on the same page.

**Pull request merged**
